# Generated by Django 2.2 on 2020-04-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200410_1003'),
        ('home', '0002_auto_20200410_1257'),
    ]

    operations = [
    ]
